/**
 * Authentication constants for server-side code
 * These are duplicated from app/constants/auth.ts to avoid import issues in Nitro bundling
 */

/**
 * Cookie name for E2E test authentication token
 * Used by automated tests to bypass Kinde OAuth flow
 */
export const E2E_TOKEN_COOKIE_NAME = 'kinde_token'

/**
 * Prefix for Symfony app tokens (used in E2E tests)
 * These are long-lived tokens generated by `php bin/console app:token:manage create`
 */
export const APP_TOKEN_PREFIX = 'app_'

/**
 * Kinde authentication cookie names (base names without prefix)
 * The prefix is configured per-project in nuxt.config.ts and applied dynamically
 */
export const KINDE_ID_TOKEN_COOKIE_NAME = 'id_token'
export const KINDE_ACCESS_TOKEN_COOKIE_NAME = 'access_token'
